import { LANGUAGES, type AnalysisResult, type SupportedLanguage } from "@/types/risk";

const RISK_LABEL: Record<string, string> = {
  high: "HIGH RISK",
  medium: "MEDIUM RISK",
  low: "LOW RISK",
};

export function buildReportText(
  result: AnalysisResult,
  fileName: string | undefined,
  language: SupportedLanguage
): string {
  const languageLabel = LANGUAGES.find((l) => l.code === language)?.label ?? "English";
  const lines: string[] = [];

  lines.push("CLAUSEWISE - DOCUMENT ANALYSIS REPORT");
  lines.push(`Document: ${fileName ?? "Pasted text"}`);
  lines.push(`Language: ${languageLabel}`);
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push(`Document type: ${result.documentType}`);
  lines.push(`Overall risk score: ${result.riskScore}/100`);
  lines.push("");
  lines.push("Summary:");
  lines.push(result.summary);
  lines.push("");
  lines.push("=".repeat(60));

  if (result.items.length === 0) {
    lines.push("");
    lines.push("No significant red flags were found in this document.");
  }

  result.items.forEach((item, i) => {
    lines.push("");
    lines.push(`${i + 1}. ${item.title} [${RISK_LABEL[item.riskLevel] ?? item.riskLevel}]`);
    lines.push(`   Clause: "${item.clauseExcerpt}"`);
    lines.push(`   What it means: ${item.explanation}`);
    lines.push(`   Why it matters: ${item.whyItMatters}`);
  });

  lines.push("");
  lines.push("=".repeat(60));
  lines.push("Generated by ClauseWise - AI analysis, not legal advice.");

  return lines.join("\n");
}

export function downloadTextFile(content: string, fileName: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
